[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/focal/mattermost-k8s-27
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  mattermost-k8s/0 [allocating] waiting: installing agent
  mattermost-k8s/1 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  mattermost-k8s/0 [idle] waiting: Waiting for database relation
  mattermost-k8s/1 [executing] waiting: Waiting for database relation
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  mattermost-k8s/0 [idle] waiting: Waiting for database relation
  mattermost-k8s/1 [idle] waiting: Waiting for database relation
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  mattermost-k8s/0 [executing] waiting: Waiting for database relation
  mattermost-k8s/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  mattermost-k8s/0 [idle] active: 
  mattermost-k8s/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  mattermost-k8s/0 [idle] active: 
  mattermost-k8s/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.1.7    unsupported  01:57:12Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Address         Exposed  Message
pgbouncer-k8s             1.21.0   active      2  pgbouncer-k8s                              0  10.152.183.212  no       
postgresql-k8s            14.11    active      3  postgresql-k8s            14/edge        232  10.152.183.19   no       
postgresql-test-app                active      1  postgresql-test-app       edge            93  10.152.183.118  no       received database credentials of the first database
self-signed-certificates           active      1  self-signed-certificates  latest/stable   72  10.152.183.24   no       

Unit                         Workload  Agent  Address      Ports  Message
pgbouncer-k8s/0              active    idle   10.1.124.72         
pgbouncer-k8s/1*             active    idle   10.1.124.73         
postgresql-k8s/0*            active    idle   10.1.124.79         Primary
postgresql-k8s/1             active    idle   10.1.124.81         
postgresql-k8s/2             active    idle   10.1.124.80         
postgresql-test-app/0*       active    idle   10.1.124.74         received database credentials of the first database
self-signed-certificates/0*  active    idle   10.1.124.75         

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-pgbouncer-k8s-2: 01:51:29 ERROR unit.pgbouncer-k8s/2.juju-log certificates:8: Non-existing secret cauth was attempted to be removed.
unit-pgbouncer-k8s-2: 01:51:29 ERROR unit.pgbouncer-k8s/2.juju-log certificates:8: Can't update secret for relation 1
unit-pgbouncer-k8s-2: 01:51:29 ERROR unit.pgbouncer-k8s/2.juju-log certificates:8: Non-existing field 'cauth' was attempted to be removed from the databag (relation ID: 1)
unit-pgbouncer-k8s-2: 01:51:29 ERROR unit.pgbouncer-k8s/2.juju-log certificates:8: Non-existing secret cert was attempted to be removed.
unit-pgbouncer-k8s-2: 01:51:29 ERROR unit.pgbouncer-k8s/2.juju-log certificates:8: Can't update secret for relation 1
unit-pgbouncer-k8s-2: 01:51:29 ERROR unit.pgbouncer-k8s/2.juju-log certificates:8: Non-existing field 'cert' was attempted to be removed from the databag (relation ID: 1)
unit-pgbouncer-k8s-2: 01:51:29 ERROR unit.pgbouncer-k8s/2.juju-log certificates:8: Non-existing secret chain was attempted to be removed.
unit-pgbouncer-k8s-2: 01:51:29 ERROR unit.pgbouncer-k8s/2.juju-log certificates:8: Can't update secret for relation 1
unit-pgbouncer-k8s-2: 01:51:29 ERROR unit.pgbouncer-k8s/2.juju-log certificates:8: Non-existing field 'chain' was attempted to be removed from the databag (relation ID: 1)

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...