[32mINFO    [0m integration.test_upgrade_from_stable:test_upgrade_from_stable.py:110 starting continuous writes to the database
[32mINFO    [0m integration.test_upgrade_from_stable:test_upgrade_from_stable.py:114 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.test_upgrade_from_stable:test_upgrade_from_stable.py:120 Refresh the charm
[32mINFO    [0m integration.test_upgrade_from_stable:test_upgrade_from_stable.py:123 Wait for upgrade to complete on first upgrading unit
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] active: 
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/2 [executing] maintenance: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] active: 
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m integration.test_upgrade_from_stable:test_upgrade_from_stable.py:131 Resume upgrade
[32mINFO    [0m integration.test_upgrade_from_stable:test_upgrade_from_stable.py:136 Wait for upgrade to complete
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [executing] maintenance: 
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] waiting: other units upgrading first...
  pgbouncer-k8s/1 [idle] active: 
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [executing] waiting: pgbouncer not running
  pgbouncer-k8s/1 [idle] active: 
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] active: 
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m integration.test_upgrade_from_stable:test_upgrade_from_stable.py:143 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.test_upgrade_from_stable:test_upgrade_from_stable.py:148 checking whether no writes were lost
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.0.142:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.6    unsupported  01:42:07Z

App                  Version  Status  Scale  Charm                Channel      Rev  Address         Exposed  Message
pgbouncer-k8s        1.21.0   active      3  pgbouncer-k8s                       0  10.152.183.67   no       
postgresql-k8s       14.13    active      3  postgresql-k8s       14/edge      464  10.152.183.176  no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  289  10.152.183.63   no       received database credentials of the first database

Unit                    Workload  Agent  Address     Ports  Message
pgbouncer-k8s/0         active    idle   10.1.82.84         
pgbouncer-k8s/1*        active    idle   10.1.82.83         
pgbouncer-k8s/2         active    idle   10.1.82.82         
postgresql-k8s/0        active    idle   10.1.82.79         
postgresql-k8s/1        active    idle   10.1.82.80         
postgresql-k8s/2*       active    idle   10.1.82.81         Primary
postgresql-test-app/0*  active    idle   10.1.82.72         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-postgresql-k8s-1: 01:35:43 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-test-app-0: 01:38:08 ERROR unit.postgresql-test-app/0.juju-log Unable to create table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 351, in _on_start_continuous_writes_action
    psycopg2.connect(self._connection_string) as connection,
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "pgbouncer-k8s-1.pgbouncer-k8s-endpoints.test.svc.cluster.local" (10.1.82.73), port 6432 failed: timeout expired

unit-postgresql-test-app-0: 01:38:08 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 565, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 364, in _on_start_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-pgbouncer-k8s-2: 01:39:11 ERROR unit.pgbouncer-k8s/2.juju-log pgbouncer not running
unit-pgbouncer-k8s-2: 01:39:14 ERROR unit.pgbouncer-k8s/2.juju-log pgbouncer not running
unit-pgbouncer-k8s-2: 01:39:16 ERROR unit.pgbouncer-k8s/2.juju-log pgbouncer not running
unit-pgbouncer-k8s-2: 01:39:17 ERROR unit.pgbouncer-k8s/2.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:40:16 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:40:18 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:40:20 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:40:55 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:40:59 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:41:01 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:41:03 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...