[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.1.8    unsupported  01:35:55Z

App                  Version  Status   Scale  Charm                Channel   Rev  Address         Exposed  Message
pgbouncer-k8s                 waiting      3  pgbouncer-k8s        1/stable  103  10.152.183.179  no       installing agent
postgresql-k8s       14.11    waiting      3  postgresql-k8s       14/edge   250  10.152.183.62   no       installing agent
postgresql-test-app           active       1  postgresql-test-app  edge      125  10.152.183.147  no       

Unit                    Workload  Agent      Address     Ports  Message
pgbouncer-k8s/0*        error     idle       10.1.7.201         hook failed: "backend-database-relation-changed"
pgbouncer-k8s/1         error     idle       10.1.7.202         hook failed: "backend-database-relation-changed"
pgbouncer-k8s/2         error     idle       10.1.7.203         hook failed: "backend-database-relation-changed"
postgresql-k8s/0        unknown   idle       10.1.7.207         
postgresql-k8s/1*       active    executing  10.1.7.209         Primary
postgresql-k8s/2        unknown   idle       10.1.7.208         
postgresql-test-app/0*  active    idle       10.1.7.200         

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-pgbouncer-k8s-1: 01:35:54 ERROR unit.pgbouncer-k8s/1.juju-log backend-database:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/./src/charm.py", line 831, in <module>
    main(PgBouncerK8sCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/main.py", line 456, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2232, in _on_relation_changed_event
    getattr(self.on, "read_only_endpoints_changed").emit(
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/src/relations/backend_database.py", line 280, in _on_endpoints_changed
    self.charm.render_pgb_config(reload_pgbouncer=True)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/./src/charm.py", line 779, in render_pgb_config
    self.reload_pgbouncer()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/./src/charm.py", line 416, in reload_pgbouncer
    pebble_services = pgb_container.get_services()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/model.py", line 2196, in get_services
    services = self._pebble.get_services(names)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/pebble.py", line 2097, in get_services
    resp = self._request('GET', '/v1/services', query)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/pebble.py", line 1754, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/ops/pebble.py", line 1803, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/pgbouncer/pebble.socket' (container restarted?)
unit-pgbouncer-k8s-2: 01:35:54 ERROR unit.pgbouncer-k8s/2.juju-log backend-database:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/./src/charm.py", line 831, in <module>
    main(PgBouncerK8sCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/main.py", line 456, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2232, in _on_relation_changed_event
    getattr(self.on, "read_only_endpoints_changed").emit(
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/src/relations/backend_database.py", line 280, in _on_endpoints_changed
    self.charm.render_pgb_config(reload_pgbouncer=True)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/./src/charm.py", line 779, in render_pgb_config
    self.reload_pgbouncer()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/./src/charm.py", line 416, in reload_pgbouncer
    pebble_services = pgb_container.get_services()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/model.py", line 2196, in get_services
    services = self._pebble.get_services(names)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/pebble.py", line 2097, in get_services
    resp = self._request('GET', '/v1/services', query)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/pebble.py", line 1754, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/pebble.py", line 1803, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/pgbouncer/pebble.socket' (container restarted?)
unit-pgbouncer-k8s-0: 01:35:54 ERROR unit.pgbouncer-k8s/0.juju-log backend-database:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/./src/charm.py", line 831, in <module>
    main(PgBouncerK8sCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/main.py", line 456, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2232, in _on_relation_changed_event
    getattr(self.on, "read_only_endpoints_changed").emit(
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/src/relations/backend_database.py", line 280, in _on_endpoints_changed
    self.charm.render_pgb_config(reload_pgbouncer=True)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/./src/charm.py", line 779, in render_pgb_config
    self.reload_pgbouncer()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/./src/charm.py", line 416, in reload_pgbouncer
    pebble_services = pgb_container.get_services()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/model.py", line 2196, in get_services
    services = self._pebble.get_services(names)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/pebble.py", line 2097, in get_services
    resp = self._request('GET', '/v1/services', query)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/pebble.py", line 1754, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/pebble.py", line 1803, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/pgbouncer/pebble.socket' (container restarted?)

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...