[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/focal/mattermost-k8s-27
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  mattermost-k8s/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  mattermost-k8s/0 [idle] waiting: Waiting for database relation
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  mattermost-k8s/0 [idle] waiting: Waiting for database relation
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  mattermost-k8s/0 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  mattermost-k8s/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:936 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.2    unsupported  01:50:41Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Address         Exposed  Message
pgbouncer-k8s             1.21.0   active      2  pgbouncer-k8s                              0  10.152.183.50   no       
postgresql-k8s            14.15    active      3  postgresql-k8s            14/edge        509  10.152.183.191  no       
postgresql-test-app                active      1  postgresql-test-app       latest/edge    360  10.152.183.56   no       received database credentials of the first database
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  10.152.183.213  no       

Unit                         Workload  Agent  Address       Ports  Message
pgbouncer-k8s/0*             active    idle   10.1.142.201         
pgbouncer-k8s/1              active    idle   10.1.142.202         
postgresql-k8s/0             active    idle   10.1.142.209         
postgresql-k8s/1*            active    idle   10.1.142.210         Primary
postgresql-k8s/2             active    idle   10.1.142.208         
postgresql-test-app/0*       active    idle   10.1.142.203         received database credentials of the first database
self-signed-certificates/0*  active    idle   10.1.142.207         

[32mINFO    [0m pytest_operator.plugin:plugin.py:942 Juju error logs:

unit-postgresql-k8s-0: 01:39:21 ERROR unit.postgresql-k8s/0.juju-log certificates:9: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:22 ERROR unit.postgresql-k8s/2.juju-log certificates:9: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:23 ERROR unit.postgresql-k8s/0.juju-log Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-1: 01:39:23 ERROR unit.postgresql-k8s/1.juju-log certificates:9: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:24 ERROR unit.postgresql-k8s/2.juju-log Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:25 ERROR unit.postgresql-k8s/0.juju-log certificates:9: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-1: 01:39:25 ERROR unit.postgresql-k8s/1.juju-log Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:26 ERROR unit.postgresql-k8s/2.juju-log certificates:9: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:27 ERROR unit.postgresql-k8s/0.juju-log Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:27 ERROR unit.postgresql-k8s/2.juju-log Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:28 ERROR unit.postgresql-k8s/0.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:29 ERROR unit.postgresql-k8s/2.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:30 ERROR unit.postgresql-k8s/0.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:30 ERROR unit.postgresql-k8s/2.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:31 ERROR unit.postgresql-k8s/0.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:32 ERROR unit.postgresql-k8s/2.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:33 ERROR unit.postgresql-k8s/0.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:33 ERROR unit.postgresql-k8s/2.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:34 ERROR unit.postgresql-k8s/0.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:35 ERROR unit.postgresql-k8s/2.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:35 ERROR unit.postgresql-k8s/0.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:36 ERROR unit.postgresql-k8s/2.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-1: 01:39:37 ERROR unit.postgresql-k8s/1.juju-log Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:37 ERROR unit.postgresql-k8s/2.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:39 ERROR unit.postgresql-k8s/2.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:40 ERROR unit.postgresql-k8s/2.juju-log restart:5: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:41 ERROR unit.postgresql-k8s/2.juju-log restart:5: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:43 ERROR unit.postgresql-k8s/2.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:47 ERROR unit.postgresql-k8s/0.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:48 ERROR unit.postgresql-k8s/0.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-1: 01:39:48 ERROR unit.postgresql-k8s/1.juju-log certificates:9: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:39:50 ERROR unit.postgresql-k8s/0.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:54 ERROR unit.postgresql-k8s/2.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:39:55 ERROR unit.postgresql-k8s/2.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-1: 01:40:00 ERROR unit.postgresql-k8s/1.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:01 ERROR unit.postgresql-k8s/0.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:03 ERROR unit.postgresql-k8s/0.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:04 ERROR unit.postgresql-k8s/0.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:05 ERROR unit.postgresql-k8s/0.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:06 ERROR unit.postgresql-k8s/0.juju-log restart:5: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:40:07 ERROR unit.postgresql-k8s/2.juju-log restart:5: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:08 ERROR unit.postgresql-k8s/0.juju-log restart:5: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:40:09 ERROR unit.postgresql-k8s/2.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:09 ERROR unit.postgresql-k8s/0.juju-log restart:5: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:40:10 ERROR unit.postgresql-k8s/2.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:11 ERROR unit.postgresql-k8s/0.juju-log restart:5: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-1: 01:40:13 ERROR unit.postgresql-k8s/1.juju-log database:7: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:13 ERROR unit.postgresql-k8s/0.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-0: 01:40:15 ERROR unit.postgresql-k8s/0.juju-log upgrade:6: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:40:22 ERROR unit.postgresql-k8s/2.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-2: 01:40:24 ERROR unit.postgresql-k8s/2.juju-log database-peers:4: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-pgbouncer-k8s-0: 01:41:39 ERROR unit.pgbouncer-k8s/0.juju-log pgb-peers:1: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/src/charm.py", line 1138, in <module>
    main(PgBouncerK8sCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 558, in main
    manager.run()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 543, in run
    self._emit()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 499, in _emit
    self.framework.reemit()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 916, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 996, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1106, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/src/relations/pgbouncer_provider.py", line 150, in _on_database_requested
    self.charm.backend.remove_auth_function(dbs=[database])
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1106, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/src/relations/backend_database.py", line 451, in remove_auth_function
    with self.postgres._connect_to_database(dbname) as conn, conn.cursor() as cursor:
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 153, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgresql-k8s-primary.testing.svc.cluster.local" (10.152.183.186), port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.1.142.201", user "relation_id_7", database "postgresql_test_app_database", no encryption

unit-pgbouncer-k8s-0: 01:41:40 ERROR juju.worker.uniter.operation hook "pgb-peers-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-k8s-2: 01:42:58 ERROR unit.postgresql-k8s/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata

[32mINFO    [0m pytest_operator.plugin:plugin.py:1024 Forgetting model main...